name: Build and Deploy Docker

on:
  push:
    branches:
      - main  
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape pour récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Définition des variables selon l'environnement
      - name: Set environment variables
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=develop" >> $GITHUB_ENV
            echo "DATABASE_NAME=messages" >> $GITHUB_ENV
            echo "IMAGE_NAME=myappdev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DATABASE_NAME=postgres" >> $GITHUB_ENV
            echo "IMAGE_NAME=myappprod" >> $GITHUB_ENV
          else
            echo "Unsupported environment."
            exit 1
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

      # Remplacement de la base de données dans le fichier de configuration
      - name: Replace database in config file
        run: sed -i "s/^database=.*$/database=${{ env.DATABASE_NAME }}/" ./project/db/resources/database.ini

      # Construction, tag et push de l'image Docker
      - name: Build, Tag, and Push Docker Image
        run: |
          echo "Building Docker image for ${{ env.ENVIRONMENT }}..."
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy_prod:
    needs: build  # Ce job dépend du succès du job 'build'
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Exécution uniquement si un tag est poussé

    steps:
      - name: Checkout code  # Récupérer le code source du repository pour la configuration du serveur
        uses: actions/checkout@v2

      - name: Set up SSH key  # Configurer la clé SSH pour se connecter au serveur de production
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy Deploy Script to Remote Server (Prod)  # Créer un script de déploiement et le copier sur le serveur de production
        run: |
          echo '#!/bin/bash' > deploy.sh
          echo 'echo "Logging into Docker..."' >> deploy.sh
          echo 'echo "$LC_DOCKER_TOKEN" | docker login -u "$LC_DOCKER_USERNAME" --password-stdin' >> deploy.sh
          echo 'sudo docker pull $LC_DOCKER_USERNAME/myapp:latest' >> deploy.sh
          echo 'sudo docker stop myapp || true' >> deploy.sh
          echo 'sudo docker rm myapp || true' >> deploy.sh
          echo 'sudo docker run -d --name myapp -p 8088:8088 $LC_DOCKER_USERNAME/myapp:latest' >> deploy.sh
          chmod +x deploy.sh
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deploy.sh azureuser@20.19.80.212:/tmp/deploy.sh

      - name: Run Deploy Script on Remote Server (Prod)  # Exécuter le script de déploiement sur le serveur de production
        env:
          LC_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          LC_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: ssh -o StrictHostKeyChecking=no -o SendEnv=LC_DOCKER_USERNAME -o SendEnv=LC_DOCKER_TOKEN -i ~/.ssh/id_rsa azureuser@20.19.80.212 'bash /tmp/deploy.sh'

  deploy_dev:
    needs: build  # Ce job dépend du succès du job 'build'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Exécution uniquement sur la branche 'main'

    steps:
      - name: Checkout code  # Récupérer le code source du repository pour le déploiement sur le serveur dev
        uses: actions/checkout@v2

      - name: Set up SSH key  # Configurer la clé SSH pour se connecter au serveur de dev
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy Deploy Script to Remote Server (dev)  # Créer un script de déploiement et le copier sur le serveur de dev
        run: |
          echo '#!/bin/bash' > deploy.sh
          echo 'echo "Logging into Docker..."' >> deploy.sh
          echo 'echo "$LC_DOCKER_TOKEN" | docker login -u "$LC_DOCKER_USERNAME" --password-stdin' >> deploy.sh
          echo 'sudo docker pull $LC_DOCKER_USERNAME/myapp:latest' >> deploy.sh
          echo 'sudo docker stop myapp || true' >> deploy.sh
          echo 'sudo docker rm myapp || true' >> deploy.sh
          echo 'sudo docker run -d --name myapp -p 8088:8088 $LC_DOCKER_USERNAME/myapp:latest' >> deploy.sh
          chmod +x deploy.sh
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deploy.sh azureuser@20.19.81.140:/tmp/deploy.sh

      - name: Run Deploy Script on Remote Server (dev)  # Exécuter le script de déploiement sur le serveur de dev
        env:
          LC_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          LC_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: ssh -o StrictHostKeyChecking=no -o SendEnv=LC_DOCKER_USERNAME -o SendEnv=LC_DOCKER_TOKEN -i ~/.ssh/id_rsa azureuser@20.19.81.140 'bash /tmp/deploy.sh'
